### ISSUE TITLE
Add new method to POST request to /applications/{application_name}/platforms/{platform_name}/properties

### ISSUE THREAD

**Issue by dedalusium** [voyages-sncf-technologies/hesperides-jenkins-lib#15]
Currently the jenkins lib provide a method to GET platform properties but not update it.
I'm working on a PR to add one.

**Comment by Lucas-C** [comment]
Isn't `setPlatformProperties` what you are looking for ?

**Comment by dedalusium** [comment]
Oh you're right, I think i missed it because of the private visibility,
I'll update my PR to keep public method signature and use this private method

**Comment by dedalusium** [comment]
I updated my PR adding an Integration Test. Feel free to merge if it's ok.

**Comment by Lucas-C** [comment]
Closing this: PR has been merged
Thanks @dedalusium !
