### ISSUE TITLE
Disable error for no matching modules in selectModules

### ISSUE THREAD

**Issue by rbihore** [voyages-sncf-technologies/hesperides-jenkins-lib#19]
La problématique est que sur certaines plateformes, tous les modules ne sont pas installés.

Le job jenkins utilise aujourd'hui la fonction setPlatformModuleVersion, de façon itérative sur tous les modules de la note de livraison.
`

                        modules = deliveryNote.getDeliveryNoteHesperidesAllModulesDatas(trigram: jsonConfig.trigram, deliveryNote: deliveryNoteChosen)
                        echo "Hesperides Modules from delivery note: => $modules"

                        modules.each {
                            def String hesperideModuleName = it.value.hesperidesModuleName
                            def String hesperideModuleVersion = it.value.hesperidesModuleVersion

                            echo "Switch Hesperides module =>  App: $jsonConfig.trigram, Pltf: $deployPlatform, module: $hesperideModuleName, version: $hesperideModuleVersion"
                            hesperides.setPlatformModuleVersion(
                                    auth: hesperidesCredentials,
                                    app: jsonConfig.trigram,
                                    platform: deployPlatform,
                                    newVersion: hesperideModuleVersion,
                                    moduleName: hesperideModuleName,
                                    isWorkingcopy: workingCopy
                            )
                        }
`
Dans la librairie hesperides, setPlatformModuleVersion appelle ensuite selectModules, et tout cela termine en échec si le module en question n'existe pas sur la plateforme.

Est-il possible de faire renvoyer à selectModules une liste vide et un warning si le module n'est pas trouvé ?
En effet, même si certains composants sont livrés ensemble car ils ont le même cycle de vie (développement), ils ne sont pas tous susceptible d'être installé sur chaque plateforme.

Des exemple VSCT sur HUP , (avec le MOCK et les Batches).

Peut-être une autre solution en amont, dans le JenkinsFile serait préférable, mais là je ne vois pas trop sans faire du code spécifique à chaque composant.

**Comment by rbihore** [comment]
J'ai placé un contournement sur nos pipelines en m'inspirant de ce que j'ai trouvé dans la lib
`


                        def platformInfo=hesperides.getPlatformInfo(auth: hesperidesCredentials, app: jsonConfig.trigram, platform: deployPlatform)
                        
                        modules.each {
                            def String hesperideModuleName = it.value.hesperidesModuleName
                            def String hesperideModuleVersion = it.value.hesperidesModuleVersion
                            echo "Switch Hesperides module =>  App: $jsonConfig.trigram, Pltf: $deployPlatform, module: $hesperideModuleName, version: $hesperideModuleVersion"

                            def matchingModules = platformInfo.modules.findAll { it && it['name'] == hesperideModuleName }

                            if (!matchingModules) {
                                echo "No module found in platform for name $hesperideModuleName"
                            } else {
                                echo "Module $hesperideModuleName found in platform for name"
                                hesperides.setPlatformModuleVersion(
                                        auth: hesperidesCredentials,
                                        app: jsonConfig.trigram,
                                        platform: deployPlatform,
                                        newVersion: hesperideModuleVersion,
                                        moduleName: hesperideModuleName,
                                        isWorkingcopy: workingCopy
                                )
                            }
                        }
`

**Comment by Lucas-C** [comment]
Merci pour la remontée de bug @rbihore

Il me semble assez normal qu'une erreur soit levée si `setPlatformModuleVersion` est appelée avec en paramètres module qui n'existe pas sur la plateforme spécifiée.

C'est plutôt au code appelant de vérifier que le module existe bien sur cette plateforme. Ton code de "contournement" me paraît très bien en fait !

As-tu d'autres arguments qui justifieraient de modifier le comportement de `setPlatformModuleVersion` plutôt que d'utiliser ce type de logique de code ?

**Comment by chakgou** [comment]
Hello @rbihore et @Lucas-C 
A l'époque j'avais crée une fonction de matching aussi qui fonctionnait très bien. Pour l'avoir testé sur plusieurs projets:
```groovy
def filterModuleNdlWithExistedModuleHesperides(trigram, platform, hesperidesModulesAndVersionsFromNdl) {
  def infoPlaformHesperides = getInfoPlatfromHesperides(trigram, platform)

  def modules = [:]

  def moduleNamesFromHesperides = infoPlaformHesperides.modules
  .collect {
    it.name
  }

  modules = hesperidesModulesAndVersionsFromNdl.findAll{
    it.value.get('hesperidesModuleName') in moduleNamesFromHesperides
  }

  return modules

```

**Comment by Lucas-C** [comment]
Confirmé avec @rbihore : je clôture
