### ISSUE TITLE
Bug lorsque le logicGroupPath fourni à putModuleOnPlatform est préfixé d'un #

### ISSUE THREAD

**Issue by Lucas-C** [voyages-sncf-technologies/hesperides-jenkins-lib#42]
Dans ce cas, la lib envoie à l'API un `properties_path` préfixé de deux dièses

**Comment by vrenaudeau** [comment]
C'est ici le soucis : https://github.com/voyages-sncf-technologies/hesperides-jenkins-lib/blob/master/src/com/vsct/dt/hesperides/jenkins/pipelines/Hesperides.groovy#L211
